<?php /* @var $block Magento\Framework\View\Element\Template */ ?>
<div class="home-main-banner" id="main_banner">
    <div class="banner-background-image" style="background-image: url(<?php echo $block->getViewFileUrl('images/main-banner-bg.jpg'); ?>"></div>
    <div class="content">
        <div class="text-container">
            <h1 class="banner-title">We build effective e-commerce solutions for professionals in <span class="highlight">B2B</span> and <span class="highlight">B2C</span></h1>
            <div class="title-divider white">
                <div class="line"></div>
                <div class="circles"></div>
                <div class="line"></div>
            </div>
            <div class="description">
                <p>Since 2013 we’ve worked with directors, marketers and sales teams from organisations ranging in size from SME family-run businesses, to subsidiaries of multi-billion publicly traded organisations.</p>
            </div>
            <a href="<?php echo $block->getUrl('contact'); ?>" class="action primary" title="Get in touch with our team today">
                <span>Get in touch with our team today</span>
            </a>
        </div>
        <div class="browser-screenshot-container banner-image">
            <img src="<?php echo $block->getViewFileUrl('images/browser-top.svg'); ?>" class="browser-top" alt="Browser bar" />
            <img src="<?php echo $block->getViewFileUrl('images/trimline-screenshot-top-banner.jpg'); ?>" class="screenshot" alt="Trimline Group Ltd. homepage" />
        </div>
    </div>
</div>
<?php echo $block->getChildHtml('page.messages'); ?>
<div class="fullwidth-blue" id="experience">
    <div class="page-main section">
        <div class="section-intro-container">
            <h2 class="section-title center">
                <span>Why consider us</span>
            </h2>
            <div class="title-divider center">
                <div class="line"></div>
                <div class="circles"></div>
                <div class="line"></div>
            </div>
            <div class="description">Despite a challenging environment since 2020, we have helped our clients achieve:</div>
        </div>
        <div class="featured-numbers">
            <div class="feature">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/credibility/add-user.svg'); ?>" class="icon" alt="Growth in Customers Online" />
                    <div class="number">100%</div>
                    <div class="title">Growth in Customers Online</div>
                </div>
            </div>
            <div class="feature">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/credibility/order.svg'); ?>" class="icon" alt="Growth in Order Count" />
                    <div class="number">110%</div>
                    <div class="title">Growth in Order Count</div>
                </div>
            </div>
            <div class="feature">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/credibility/increase.svg'); ?>" class="icon" alt="Turnover Growth Online" />
                    <div class="number">107%</div>
                    <div class="title">Turnover Growth Online</div>
                </div>
            </div>
        </div>
        <div class="info-boxes">
            <div class="info-box award">
                <div class="inner-wrapper">
                    <div class="text-container">
                        <div class="description">Our efforts were recognised with one of our clients winning their industry award for best e-commerce website.</div>
                        <a href="https://www.tilezine.co.uk/2501-2/" target="_blank" class="action primary dark">
                            <span>View Award</span>
                        </a>
                    </div>
                    <div class="icon-container">
                        <img src="<?php echo $block->getViewFileUrl('images/icons/first-laurel-blue.svg'); ?>" class="icon" alt="Award laurel" />
                    </div>
                </div>
            </div>
            <div class="info-box magento">
                <div class="inner-wrapper">
                    <div class="text-container">
                        <div class="description">We are certified Magento developers, one of the world’s leading e-commerce platforms with over 15,000 installations in the UK.</div>
                        <div class="certifications">
                            <img src="<?php echo $block->getViewFileUrl('images/certifications/developer.png'); ?>" class="cert" alt="Magento Developer Certification">
                            <img src="<?php echo $block->getViewFileUrl('images/certifications/front-end.png'); ?>" class="cert" alt="Magento Front End Developer">
                            <img src="<?php echo $block->getViewFileUrl('images/certifications/solution-specialist.png'); ?>" class="cert" alt="Magento Solution Specialist Certification">
                        </div>
                    </div>
                    <div class="icon-container">
                        <img src="<?php echo $block->getViewFileUrl('images/icons/magento-logo.svg'); ?>" class="icon" alt="Magento logo" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fullwith" id="markets_served">
    <div class="section">
        <div class="section-intro-container">
            <h2 class="section-title center">
                <span>Our work</span>
            </h2>
            <div class="title-divider center">
                <div class="line"></div>
                <div class="circles"></div>
                <div class="line"></div>
            </div>
            <div class="description">We help directors, managing directors, marketing professionals, business developers and sales teams in B2B and B2C solve business problems using technology and e-commerce.</div>
        </div>
        <div class="case-studies-outer-wrapper">
            <div class="case-study-slider">
                <ul class="case-study-list">
                    <li class="case-study-item trimline">
                        <div class="case-study-container">
                            <div class="image-container">
                                <img src="<?php echo $block->getViewFileUrl('images/case-studies/trimline/background-shapes.svg'); ?>" class="background-shapes" alt="Trimline background shapes" />
                                <img src="<?php echo $block->getViewFileUrl('images/case-studies/trimline/screenshot.png'); ?>" alt="Trimline Group Ltd. screenshot" class="screenshot" />
                            </div>
                            <div class="text-container">
                                <div class="content">
                                    <div class="title">Trimline Group Ltd.</div>
                                    <div class="subheading">Magento 2 Project</div>
                                    <div class="description">We worked with Trimline’s marketing team and won them the award for best e-commerce website in their industry. During this project we built a completely bespoke reward scheme that as of early 2022 has processed over £33.3m worth of trade and at present, we are working with the team to launch an exciting new subrand.</div>
                                    <a href="https://www.trimlinegroup.com/" class="action primary" target="_blank">
                                        <span>Visit Website</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="case-study-item howsafe">
                        <div class="case-study-container">
                            <div class="image-container">
                                <img src="<?php echo $block->getViewFileUrl('images/case-studies/howsafe/background-shapes.svg'); ?>" class="background-shapes" alt="Howsafe background shapes" />
                                <img src="<?php echo $block->getViewFileUrl('images/case-studies/howsafe/screenshot.png'); ?>" alt="Howsafe screenshot" class="screenshot" />
                            </div>
                            <div class="text-container">
                                <div class="content">
                                    <div class="title">Howsafe</div>
                                    <div class="subheading">Magento 2 Project</div>
                                    <div class="description">Working with the director and sales manager to keep the business at the forefront of the industry, we improved the customer experience by using software most modern customers' look for during their journey, such as FAQS, product features, related products, reviews and product customisations.</div>
                                    <a href="https://www.howsafe.co.uk/" class="action primary" target="_blank">
                                        <span>Visit Website</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="case-study-item venhill">
                        <div class="case-study-container">
                            <div class="image-container">
                                <img src="<?php echo $block->getViewFileUrl('images/case-studies/venhill/background-shapes.svg'); ?>" class="background-shapes" alt="Venhill Engineering background shapes" />
                                <img src="<?php echo $block->getViewFileUrl('images/case-studies/venhill/screenshot.png'); ?>" alt="Venhill Engineering screenshot" class="screenshot" />
                            </div>
                            <div class="text-container">
                                <div class="content">
                                    <div class="title">Venhill Engineering</div>
                                    <div class="subheading">Magento 2 Project</div>
                                    <div class="description">
                                        <p>Working with the director and operations manager on this project, we built a bespoke line builder to allow customers to create their own products and likewise a part finder to improve the ease of use when searching for specific products.</p>
                                        <p>This was a further addition to using software most modern customers' look for during their journey, such as FAQS, product features, related products, reviews and product customisations.</p>
                                    </div>
                                    <a href="https://venhill.co.uk/" class="action primary" target="_blank">
                                        <span>Visit Website</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="slider-controls">
                <div class="swiper-control case-study-slider-left"></div>
                <div class="swiper-control case-study-slider-right"></div>
            </div>
        </div>
        <div class="swiper-container case-study-thumbnails">
            <ul class="swiper-wrapper">
                <li class="swiper-slide logo-thumbnail-container">
                    <div class="inner-wrapper">
                        <img src="<?php echo $block->getViewFileUrl('images/case-studies/logos/trimline.svg'); ?>" class="normal-logo" alt="Trimline Group Ltd. logo" />
                        <img src="<?php echo $block->getViewFileUrl('images/case-studies/logos/trimline-grey.svg'); ?>" class="grey-logo" alt="Trimline Group Ltd. grey logo" />
                    </div>
                </li>
                <li class="swiper-slide logo-thumbnail-container">
                    <div class="inner-wrapper">
                        <img src="<?php echo $block->getViewFileUrl('images/case-studies/logos/howsafe.svg'); ?>" class="normal-logo" alt="Howsafe logo" />
                        <img src="<?php echo $block->getViewFileUrl('images/case-studies/logos/howsafe-grey.svg'); ?>" class="grey-logo" alt="Howsafe grey logo" />
                    </div>
                </li>
                <li class="swiper-slide logo-thumbnail-container">
                    <div class="inner-wrapper">
                        <img src="<?php echo $block->getViewFileUrl('images/case-studies/logos/venhill.svg'); ?>" class="normal-logo" alt="Venhill Engineering logo" />
                        <img src="<?php echo $block->getViewFileUrl('images/case-studies/logos/venhill-grey.svg'); ?>" class="grey-logo" alt="Venhill Engineering grey logo" />
                    </div>
                </li>
            </ul>
        </div>
        <script>
            requirejs(['jquery', 'js/lib/swiper'], function($, Swiper) {
                var lastCaseStudyState;

                var responsiveCaseStudy = {
                    onResize: function () {
                        $(window).resize(function () {
                            responsiveCaseStudy.checkWidth();
                        });
                    },
                    checkWidth: function () {
                        if (window.innerWidth >= 768) {
                            if (lastCaseStudyState !== 'desktop') {
                                lastCaseStudyState = 'desktop';
                                responsiveCaseStudy.desktop();
                            }
                        } else {
                            if (lastCaseStudyState !== 'mobile') {
                                lastCaseStudyState = 'mobile';
                                responsiveCaseStudy.mobile();
                            }
                        }
                    },
                    desktop: function () {
                        $('.case-study-slider').removeClass('swiper-container')
                            .find('ul').removeClass('swiper-wrapper')
                            .find('li').removeClass('swiper-slide');
                        $('.case-study-slider *').removeAttr('style');
                    },
                    mobile: function () {
                        $('.case-study-slider').addClass('swiper-container')
                            .find('ul').addClass('swiper-wrapper')
                            .find('li').addClass('swiper-slide');
                        var caseStudiesSlider = new Swiper('.case-study-slider', {
                            speed: 600,
                            spaceBetween: 100,
                            roundLengths: true,
                            navigation: {
                                prevEl: '.case-study-slider-left',
                                nextEl: '.case-study-slider-right'
                            }
                        });
                        var caseStudiesSliderThumbs = new Swiper('.case-study-thumbnails', {
                            spaceBetween: 10,
                            preventClicks: false,
                            preventClicksPropagation: false,
                            slideToClickedSlide: true,
                            centeredSlides: true,
                            slidesPerView: 'auto',
                            shortSwipes: false,
                            longSwipes: true,
                            longSwipesRatio: 1,
                            roundLengths: true,
                            speed: 600,
                            allowTouchMove: false,
                            breakpoints: {
                                768: {
                                    spaceBetween: 20
                                }
                            }
                        });
                        caseStudiesSlider.controller.control = caseStudiesSliderThumbs;
                        caseStudiesSliderThumbs.controller.control = caseStudiesSlider;
                    },
                    init: function () {
                        this.onResize();
                        this.checkWidth();
                    }
                };

                responsiveCaseStudy.init();
            });
        </script>
    </div>
</div>
<div class="fullwidth-blue" id="services">
    <div class="page-main section">
        <div class="section-intro-container">
            <h2 class="section-title center">
                <span>Problems we solve</span>
            </h2>
            <div class="title-divider center">
                <div class="line"></div>
                <div class="circles"></div>
                <div class="line"></div>
            </div>
            <div class="description">Many of our clients come to us with one or more of the following issues:</div>
        </div>
        <div class="problems-list">
            <div class="problem">
                <div class="image-container">
                    <img src="<?php echo $block->getViewFileUrl('images/services/illustrations/where-to-start.svg'); ?>" class="image" alt="Knowing where to start" />
                </div>
                <div class="text-container">
                    <div class="title">Knowing where to start</div>
                    <div class="description">
                        <p>Many professionals have envisioned exactly what they want when it comes to a new website, but knowing where to start, what’s required for a complete plan or communicating exactly what is wanted often presents itself as an early challenge.</p>
                        <p>Without being an expert in e-commerce, documenting and gathering requirements, knowing what figures to look at, facilitating and leading meetings and actively partaking in ideation to translate and record into technical requirements is tough -  as is knowing costs, timescales and return on investments - that’s where we come in!</p>
                        <p>We use a specialist, experienced approach to give guidance and direction when starting a project.</p>
                    </div>
                </div>
            </div>
            <div class="problem">
                <div class="image-container">
                    <img src="<?php echo $block->getViewFileUrl('images/services/illustrations/building-plan.svg'); ?>" class="image" alt="Building a business-case plan" />
                </div>
                <div class="text-container">
                    <div class="title">Building a business-case plan</div>
                    <div class="description">
                        <p>Organisations know what they want, but how exactly do they get it?</p>
                        <p>Clients often need support in building a business case that demonstrates and justifies what actually needs to be done to achieve success: A thorough analysis of the overall business, needs and figures help to build a plan that demonstrates the direction of travel and the technology required to get there (this is often referred to as the internal resource for justification).</p>
                    </div>
                </div>
            </div>
            <div class="problem">
                <div class="image-container">
                    <img src="<?php echo $block->getViewFileUrl('images/services/illustrations/online-offline.svg'); ?>" class="image" alt="Defining how offline and online work together" />
                </div>
                <div class="text-container">
                    <div class="title">Defining how offline and online work together</div>
                    <div class="description">
                        <p>Websites can serve online and beyond, with no disruption to the status quo.</p>
                        <p>With zero interruptions, online functions can successfully support offline teams and users, for example, a website can digitally replicate in person services (such as customer support) whilst improving the efficiency of processes (for example, the processing of the product) by being in sync with back end systems to streamline the functionality of departments: a benefit being the removal of unnecessary administrative hours and resources, boosting staff morale and productivity. </p>
                    </div>
                </div>
            </div>
            <div class="problem">
                <div class="image-container">
                    <img src="<?php echo $block->getViewFileUrl('images/services/illustrations/data-analysis.svg'); ?>" class="image" alt="Using analytics and interpreting reports to generate strategy" />
                </div>
                <div class="text-container">
                    <div class="title">Using analytics and interpreting reports to generate strategy</div>
                    <div class="description">
                        <p>Used intelligently, a website can generate strategic ideas and direct commercial focus.</p>
                        <p>Think of it as a reporting tool that surfaces opportunities (or warnings) to direct commercial focus and strategy by gaining regular-live awareness into customer behaviour, data and natural phenomenons that give insight to improve areas such as the customer experience and SEO.</p>
                    </div>
                </div>
            </div>
            <div class="problem">
                <div class="image-container">
                    <img src="<?php echo $block->getViewFileUrl('images/services/illustrations/build-trust.svg'); ?>" class="image" alt="Building trust and commitment" />
                </div>
                <div class="text-container">
                    <div class="title">Building trust and commitment</div>
                    <div class="description">
                        <p>More so now than ever, we understand the need to demonstrate trust between client and supplier.</p>
                        <p>With the recent surge in b2b e-commerce, websites have been built despite a lack of vital context - but how can a supplier be trusted to build a website that will most meaningfully move the business forward? By seeking to get an extensive understanding of the business by looking at:</p>
                        <ul>
                            <li>Customer segments</li>
                            <li>Employees</li>
                            <li>Business model</li>
                            <li>Product types</li>
                            <li>Bespoke software</li>
                            <li>Objectives</li>
                            <li>Company data and competitors</li>
                        </ul>
                        <p>Without this, a supplier cannot be trusted to build the best possible website for the client.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fullwidth" id="approach">
    <div class="section">
        <div class="section-intro-container">
            <h2 class="section-title center">
                <span>How it's done</span>
            </h2>
            <div class="title-divider center">
                <div class="line"></div>
                <div class="circles"></div>
                <div class="line"></div>
            </div>
            <div class="description">We plan, launch, and help run websites with the following key foundations:</div>
        </div>
        <div class="how-its-done-steps-wrapper our-approach-slider swiper-container">
            <div class="how-its-done-steps swiper-wrapper">
                <div class="step swiper-slide">
                    <div class="inner-wrapper">
                        <div class="icon">
                            <img src="<?php echo $block->getViewFileUrl('images/icons/approach/approach.svg'); ?>" alt="Initial consultation icon" />
                        </div>
                        <div class="content">
                            <div class="subtitle">Overview</div>
                            <div class="title">Our approach</div>
                            <div class="description">
                                <p>To build the best fit website for our clients, we specialise in taking the time to get the deepest possible understanding of the business and the industry it operates in. With a decade of experience, passion for solving problems and expertise of asking all the right questions, we develop hassle-free project plans that enable a website to be built to exact specifications and expectations.</p>
                                <p>We value a consultative approach to creating a proposal, adding depth and detail at each stage of planning, while evaluating together to ensure the plan consistently represents the best overall fit for the business: and we never progress without echoing back our understanding, ensuring clients are confident we understand the most complex of requests and they know how what they want is achieved.</p>
                            </div>
                        </div>
                        <a href="#" class="action primary next-slide dark-l">
                            <span>First Step</span>
                        </a>
                    </div>
                </div>
                <div class="step swiper-slide">
                    <div class="inner-wrapper">
                        <div class="icon">
                            <img src="<?php echo $block->getViewFileUrl('images/icons/approach/consultation.svg'); ?>" alt="Initial consultation icon" />
                        </div>
                        <div class="content">
                            <div class="subtitle">Step 1</div>
                            <div class="title">Initial consultation</div>
                            <div class="description">
                                <p>An initial open-talk to delve into the business to identify the challenges of the current website, future aspirations, product types and target markets, as well as project expectations and limitations, (for example, how can our team best support client job roles and departments) and lastly: timelines and figures to be met/improved.</p>
                                <p>We use this opportunity to also learn about bespoke or uncommon features the website currently uses or would benefit from. This stage is the starting foundation as to what a solution to the challenges could include.</p>
                            </div>
                        </div>
                        <a href="#" class="action primary next-slide dark-l">
                            <span>Next Step</span>
                        </a>
                    </div>
                </div>
                <div class="step swiper-slide">
                    <div class="inner-wrapper">
                        <div class="icon">
                            <img src="<?php echo $block->getViewFileUrl('images/icons/approach/puzzle.svg'); ?>" alt="Knowing what to do icon" />
                        </div>
                        <div class="content">
                            <div class="subtitle">Step 2</div>
                            <div class="title">Knowing what to do</div>
                            <div class="description">
                                <p>The biggest question we hear when developing websites is ‘but how exactly do we get that?’ Let us answer it now.</p>
                                <p>Knowing the business and the specific requirements, we isolate the metrics (associated with the particular objective) that need to be influenced to meet success and carefully match them with technology, techniques or bespoke software to create the desirable outcome, presenting a solution evidenced with data. In other terms, we look at exactly what is wanted and what needs to be done to get there.</p>
                            </div>
                            <a href="#" class="action primary modal-open" data-type="knowing-what-to-do">
                                <span>See Example</span>
                            </a>
                        </div>
                        <a href="#" class="action primary next-slide dark-l">
                            <span>Next Step</span>
                        </a>
                    </div>
                </div>
                <div class="step swiper-slide">
                    <div class="inner-wrapper">
                        <div class="icon">
                            <img src="<?php echo $block->getViewFileUrl('images/icons/approach/summary.svg'); ?>" alt="Executive summary icon" />
                        </div>
                        <dic class="content">
                            <div class="subtitle">Step 3</div>
                            <div class="title">Executive summary</div>
                            <div class="description">
                                <p>Following the call, we take what we initially discussed and present/echo back an executive summary of the business change required, indicative costs and timescales and how the return on investment will be realised (substantially helping clients who request support for internally justifying costs).</p>
                            </div>
                        </dic>
                        <a href="#" class="action primary next-slide dark-l">
                            <span>Next Step</span>
                        </a>
                    </div>
                </div>
                <div class="step swiper-slide">
                    <div class="inner-wrapper">
                        <div class="icon">
                            <img src="<?php echo $block->getViewFileUrl('images/icons/approach/detailed-plan.svg'); ?>" alt="Final proposal icon" />
                        </div>
                        <div class="content">
                            <div class="subtitle">Step 4</div>
                            <div class="title">Final proposal</div>
                            <div class="description">
                                <p>The final proposal consists of a full work breakdown schedule, detailing all costs, timescales and requirements, and having adopted a consultative process, we ensure  what is being presented internally/to stakeholders represents the best overall fit (ensuring you look good to colleagues and superiors!).</p>
                            </div>
                        </div>
                        <a href="#" class="action primary next-slide dark-l">
                            <span>Next Step</span>
                        </a>
                    </div>
                </div>
                <div class="step swiper-slide">
                    <div class="inner-wrapper">
                        <div class="icon">
                            <img src="<?php echo $block->getViewFileUrl('images/icons/approach/web-development.svg'); ?>" alt="Web development icon" />
                        </div>
                        <div class="content">
                            <div class="subtitle">Step 5</div>
                            <div class="title">Execution</div>
                            <div class="description">
                                <p>It’s time to build a website and deliver a project exactly to specification - to standard, websites support the customer journey, work across mobile/tablet/desktop, are intuitive and easy to navigate, integrate with existing systems, are search engine optimised (reducing external fees) and finally, are secure and stable.</p>
                            </div>
                        </div>
                        <a href="#" class="action primary next-slide dark-l">
                            <span>Next Step</span>
                        </a>
                    </div>
                </div>
                <div class="step swiper-slide">
                    <div class="inner-wrapper">
                        <div class="icon">
                            <img src="<?php echo $block->getViewFileUrl('images/icons/approach/ongoing-support.svg'); ?>" alt="Ongoing support icon" />
                        </div>
                        <div class="content">
                            <div class="subtitle">Step 6</div>
                            <div class="title">Ongoing</div>
                            <div class="description">
                                <p>We facilitate check-in meetings and provide extensive training throughout the project, and having integrated ourselves as part of the team, we are always on hand to help and look forward to seeing clients' success.</p>
                                <p>As a flexible team, we often build upon and make modifications to existing features, seeing them evolve with enhancements overtime. For example, the bespoke reward scheme built for our client was enhanced to enable their customers to redeem points against their extensive catalogue rather than popular main street gifts, making 2,700 of their own stock items redeemable.</p>
                                <p>Sometimes, clients prefer to approach a project by selecting ‘mini-projects’ within a larger project, allowing them to essentially pick and choose what will be executed first and what will be developed in the future - Rome wasn’t built overnight! </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-container our-approach-thumbnails">
            <div class="swiper-wrapper"></div>
        </div>
        <div class="modal-wrapper" data-type="knowing-what-to-do">
            <div class="modal-window modal-case-study">
                <div class="close close-icon"></div>
                <img src="<?php echo $block->getViewFileUrl('images/case-studies/trimline/background-shapes-small.svg'); ?>" class="background-shapes" alt="Trimline background shapes" />
                <div class="modal-window-inner">
                    <div class="modal-case-study-content">
                        <div class="image-container">
                            <img src="<?php echo $block->getViewFileUrl('images/case-studies/trimline/t-points-mobile-screenshot.png'); ?>" alt="Trimline Group Ltd. mobile screenshot" class="screenshot" />
                        </div>
                        <div class="text-container">
                            <h2 class="modal-title">
                                <span>Transforming an idea into reality</span>
                            </h2>
                            <div class="description">
                                <p>We worked with Trimline’s marketing team and won them the award for best e-commerce website in their industry. During this project we built a completely bespoke reward scheme that as of early 2022 has processed over £33.3m worth of trade and at present, we are working with the team to launch an exciting new subrand.</p>
                            </div>
                            <a href="#" class="action primary dark close">
                                <span>Close</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            requirejs(['jquery', 'js/lib/swiper'], function($, Swiper) {
                $('.how-its-done-steps > .step').each(function() {
                    $(this).find('.icon').clone().addClass('swiper-slide').appendTo('.our-approach-thumbnails > .swiper-wrapper');
                });

                var ourApproachSlider = new Swiper('.our-approach-slider', {
                    speed: 600,
                    direction: "horizontal",
                    spaceBetween: 10,
                    effect: "coverflow",
                    grabCursor: true,
                    centeredSlides: true,
                    roundLengths: true,
                    slidesPerView: "auto",
                    coverflowEffect: {
                        rotate: 50,
                        stretch: 0,
                        depth: 300,
                        modifier: 1,
                        slideShadows: true
                    },
                    breakpoints: {
                        380: {
                            spaceBetween: 20
                        },
                        768: {
                            spaceBetween: 40,
                        },
                        1240: {
                            spaceBetween: 50
                        },
                        1600: {
                            spaceBetween: 60
                        }
                    }
                });

                var ourApproachSliderThumbs = new Swiper('.our-approach-thumbnails', {
                    spaceBetween: 10,
                    preventClicks: false,
                    preventClicksPropagation: false,
                    slideToClickedSlide: true,
                    centeredSlides: true,
                    slidesPerView: 'auto',
                    shortSwipes: false,
                    longSwipes: true,
                    longSwipesRatio: 1,
                    roundLengths: true,
                    speed: 600,
                    allowTouchMove: false,
                    breakpoints: {
                        768: {
                            spaceBetween: 14
                        }
                    }
                });
                ourApproachSlider.controller.control = ourApproachSliderThumbs;
                ourApproachSliderThumbs.controller.control = ourApproachSlider;

                $('.action.next-slide').click(function(e) {
                    e.preventDefault();
                    ourApproachSlider.slideNext();
                });
            });
        </script>
    </div>
</div>
<div class="fullwidth" id="results">
    <div class="section">
        <div class="page-main">
            <div class="section-intro-container">
                <h2 class="section-title center">
                    <span>Key benefits</span>
                </h2>
                <div class="title-divider center white">
                    <div class="line"></div>
                    <div class="circles"></div>
                    <div class="line"></div>
                </div>
                <div class="description" style="color: #fff">As well as a free-to-take, personalised project plan, when working with us you also receive the following:</div>
            </div>
        </div>
        <div class="results-list">
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/calculator.svg'); ?>" alt="Free data resources" class="icon" />
                    <div class="title">Free data resources</div>
                    <div class="description">copies of the ‘number crunching’ that provided the solution as to what to do</div>
                </div>
            </div>
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/support-role.svg'); ?>" alt="Support with role " class="icon" />
                    <div class="title">Support with role</div>
                    <div class="description">we are committed to ensuring professionals succeed at the task at hand, making even those with little experience look and feel confident in the e-commerce world</div>
                </div>
            </div>
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/stopwatch.svg'); ?>" alt="Quick turnaround" class="icon" />
                    <div class="title">Quick turnaround</div>
                    <div class="description">speedy response on timescales and costs associated</div>
                </div>
            </div>
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/thumbs-up.svg'); ?>" alt="Meeting management" class="icon" />
                    <div class="title">Meeting management</div>
                    <div class="description">with great feedback on how we manage meetings, rest assured we’ll do the heavy work of facilitating and leading contact</div>
                </div>
            </div>
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/hand-support-chart.svg'); ?>" alt="Extensive SEO insurance" class="icon" />
                    <div class="title">Extensive SEO insurance</div>
                    <div class="description">zero disruption to traffic or prior SEO efforts</div>
                </div>
            </div>
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/price-tag.svg'); ?>" alt="Guarantee" class="icon" />
                    <div class="title">Guarantee</div>
                    <div class="description">our costs will be covered by a profit uplift, or we will refund any difference in cash</div>
                </div>
            </div>
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/training.svg'); ?>" alt="Training included" class="icon" />
                    <div class="title">Training included</div>
                    <div class="description">all projects come with 1:1 training sessions, handbooks, check in meetings and ongoing support</div>
                </div>
            </div>
            <div class="result">
                <div class="inner-wrapper">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/benefits/team-extension.svg'); ?>" alt="Trusted team" class="icon" />
                    <div class="title">Trusted team</div>
                    <div class="description">we are a friendly, flexible bunch who become an extension of your team</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fullwidth-blue" id="about">
    <div class="page-main section">
        <div class="section-intro-container">
            <h2 class="section-title center">
                <span>About Us</span>
            </h2>
            <div class="title-divider center">
                <div class="line"></div>
                <div class="circles"></div>
                <div class="line"></div>
            </div>
            <div class="description">Our drive is rooted in the belief that professionals from all backgrounds with different levels of experience can still be involved in building successful e-commerce projects: we’ll do the heavy lifting, as it’s our problem to be the IT experts, not yours.</div>
        </div>
        <div class="team-members">
            <div class="member">
                <div class="inner-wrapper">
                    <div class="image-container">
                        <img src="<?php echo $block->getViewFileUrl('images/team/avatar/james.svg'); ?>" class="image" alt="James" />
                    </div>
                    <div class="content">
                        <div class="name">James</div>
                        <div class="job-role">Managing Director</div>
                        <div class="description">Lorem ipsum dolor sit amet, ad mea graeco intellegam, his in propriae persecuti intellegam.</div>
                        <a href="https://www.linkedin.com/in/jrwithers/" class="linkedin-link action primary">
                            <span>View Linked-In</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="member">
                <div class="inner-wrapper">
                    <div class="image-container">
                        <img src="<?php echo $block->getViewFileUrl('images/team/avatar/alex.svg'); ?>" class="image" alt="Alex" />
                    </div>
                    <div class="content">
                        <div class="name">Alex</div>
                        <div class="job-role">Lead Developer</div>
                        <div class="description">Lorem ipsum dolor sit amet, ad mea graeco intellegam, his in propriae persecuti intellegam.</div>
                        <a href="https://www.linkedin.com/in/jrwithers/" class="linkedin-link action primary">
                            <span>View Linked-In</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="member">
                <div class="inner-wrapper">
                    <div class="image-container">
                        <img src="<?php echo $block->getViewFileUrl('images/team/avatar/trent.svg'); ?>" class="image" alt="Trent" />
                    </div>
                    <div class="content">
                        <div class="name">Trent</div>
                        <div class="job-role">Lead Designer</div>
                        <div class="description">Lorem ipsum dolor sit amet, ad mea graeco intellegam, his in propriae persecuti intellegam.</div>
                        <a href="https://www.linkedin.com/in/trent-riddington-53a851150/" class="linkedin-link action primary">
                            <span>View Linked-In</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="member">
                <div class="inner-wrapper">
                    <div class="image-container">
                        <img src="<?php echo $block->getViewFileUrl('images/team/avatar/chloe.svg'); ?>" class="image" alt="Chloe" />
                    </div>
                    <div class="content">
                        <div class="name">Chloe</div>
                        <div class="job-role">Marketing Strategist</div>
                        <div class="description">Lorem ipsum dolor sit amet, ad mea graeco intellegam, his in propriae persecuti intellegam.</div>
                        <a href="https://www.linkedin.com/in/chloe-joomun-7a82a6159/" class="linkedin-link action primary">
                            <span>View Linked-In</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="team-aims-wrapper section">
        <div class="page-main">
            <div class="small-title">
                <span>A small yet mighty team, everyday we aim to get:</span>
            </div>
        </div>
        <div class="swiper-container team-aims-slider">
            <div class="swiper-wrapper team-aims">
                <div class="aim swiper-slide">
                    <div class="inner-wrapper">The deepest understanding of the needs of customers</div>
                </div>
                <div class="aim swiper-slide">
                    <div class="inner-wrapper">Comprehensive knowledge of the software and services that are best for each customer</div>
                </div>
                <div class="aim swiper-slide">
                    <div class="inner-wrapper">A focus on re-usable software products that give us the ability to effectively create something new from something existing</div>
                </div>
                <div class="aim swiper-slide">
                    <div class="inner-wrapper">High utilisation, at the same time as being ready to spring into action when needed</div>
                </div>
                <div class="aim swiper-slide">
                    <div class="inner-wrapper">A culture of personal, friendly, knowledgeable service, unlike what some IT organisations offer</div>
                </div>
                <div class="aim swiper-slide">
                    <div class="inner-wrapper">A central and all-encompassing emphasis on ensuring consistent high-quality customer experiences</div>
                </div>
                <div class="aim swiper-slide">
                    <div class="inner-wrapper">A supportive team of future-facing, service-focused individuals; committed to personal, and stakeholder growth</div>
                </div>
            </div>
        </div>
    </div>
    <script>
        requirejs(['jquery', 'js/lib/swiper'], function($, Swiper) {
            var teamAimsSlider = new Swiper('.team-aims-slider', {
                speed: 600,
                spaceBetween: 1,
                roundLengths: true,
                slidesPerView: 2,
                loop: true,
                autoplay: {
                    delay: 500000
                },
                breakpoints: {
                    768: {
                        slidesPerView: 3,
                        autoplay: {
                            delay: 5000
                        }
                    },
                    1240: {
                        slidesPerView: 5
                    },
                    1600: {
                        slidesPerView: 7
                    }
                }
            });
        });
    </script>
</div>
