<?php /* @var $block Magento\Framework\View\Element\Template */ ?>
<header class="page-header">
    <div class="page-main">
        <a href="<?php echo $block->getUrl(''); ?>" class="logo anchor-link">
            <img src="<?php echo $block->getViewFileUrl('images/logo.svg'); ?>" alt="Audere Commerce logo" />
        </a>
        <ul class="main-navigation" id="main_navigation">
            <li><a href="#experience" title="Experience">Experience</a></li>
            <li><a href="#markets_served" title="Markets served">Markets served</a></li>
            <li><a href="#services" title="Services">Services</a></li>
            <li><a href="#approach" title="Approach">Approach</a></li>
            <li><a href="#results" title="Results">Results</a></li>
            <li><a href="#about" title="About">About</a></li>
            <li class="button">
                <a href="<?php echo $block->getUrl('contact'); ?>" title="Contact" class="action primary">
                    <span>Contact</span>
                </a>
            </li>
        </ul>
        <div id="menu_icon">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</header>
