<?php /* @var $block Magento\Framework\View\Element\Template */ ?>
<div class="col contact-details-col">
    <h2 class="section-title">
        <span><?php echo __('Contact Details'); ?></span>
    </h2>
    <ul class="contact-details">
        <li class="address">
            <div class="icon"></div>
            <span>Audere Commerce, Monkswell House, Monkswell park, Knaresborough HG5 8NQ</span>
        </li>
        <li class="email">
            <div class="icon"></div>
            <a href="mailto:contact@auderecommerce.com">contact@auderecommerce.com</a>
        </li>
        <li class="phone">
            <div class="icon"></div>
            <a href="tel:03330116909">0333 011 6909</a>
        </li>
    </ul>
    <div class="team-members">
        <div class="member">
            <div class="inner-wrapper">
                <div class="image-container">
                    <img src="<?php echo $block->getViewFileUrl('images/team/avatar/james.svg'); ?>" class="image" alt="James" />
                </div>
                <div class="content">
                    <div class="name">James</div>
                    <div class="job-role">Managing Director</div>
                    <div class="description">Lorem ipsum dolor sit amet, ad mea graeco intellegam, his in propriae persecuti intellegam.</div>
                    <a href="https://www.linkedin.com/in/jrwithers/" class="linkedin-link action primary">
                        <span>View Linked-In</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="member">
            <div class="inner-wrapper">
                <div class="image-container">
                    <img src="<?php echo $block->getViewFileUrl('images/team/avatar/chloe.svg'); ?>" class="image" alt="Chloe" />
                </div>
                <div class="content">
                    <div class="name">Chloe</div>
                    <div class="job-role">Marketing Strategist</div>
                    <div class="description">Lorem ipsum dolor sit amet, ad mea graeco intellegam, his in propriae persecuti intellegam.</div>
                    <a href="https://www.linkedin.com/in/chloe-joomun-7a82a6159/" class="linkedin-link action primary">
                        <span>View Linked-In</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
