<?php /* @var $block Magento\Framework\View\Element\Template */ ?>
<div class="fullwidth-top-banner">
    <div class="content">
        <div class="text-container">
            <?php echo $block->getChildHtml('page.main.title'); ?>
            <div class="title-divider white">
                <div class="line"></div>
                <div class="circles"></div>
                <div class="line"></div>
            </div>
            <div class="description">We're a friendly bunch of people happy to answer questions with zero obligation. If you'd like to share more about your business needs and wants, we'll thank you with selection of leading Yorkshire beers, or the famous Betty's of Harrogate luxury tea and biscuits</div>
        </div>
    </div>
</div>
