<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
$limit = 220;
$shortDescription = strip_tags(str_replace('&nbsp;', '', $block->getShorContent()));
$blogHelper = $this->helper('AudereCommerce\AudereCommerce\Helper\Blog');
/* @var $blogHelper AudereCommerce\AudereCommerce\Helper\Blog */
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <?php if ($featuredImage = $_post->getFeaturedImage()): ?>
        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>" class="image" style="background-image: url(<?php echo $featuredImage ?>);"></a>
    <?php endif; ?>
    <div class="content">
        <div class="top">
            <?php if ($postCategory = $blogHelper->getPostCategory($_post->getId())): ?>
                <a href="<?php echo $blogHelper->getBlogCategoryUrl($postCategory); ?>" class="post-category">
                    <span><?php echo $postCategory->getData('title'); ?></span>
                </a>
            <?php endif; ?>
            <div class="date"><?php echo $_post->getPublishDate('F d, Y') ?></div>
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?php echo $_postUrl ?>">
                    <?php echo $_postName; ?>
                </a>
            </h2>
            <div class="post-description clearfix">
                <div class="post-text-hld clearfix">
                    <?php if (strlen($shortDescription) > $limit): ?>
                        <?php echo substr($shortDescription, 0, strrpos(substr($shortDescription, 0, $limit), ' ')) . '...'; ?>
                    <?php else: ?>
                        <?php echo $shortDescription; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="bottom">
            <a class="action primary" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                <?php echo __('Find Out More') ?>
            </a>
        </div>
    </div>
</li>
