<?php /* @var $block AudereCommerce\KnowledgeBase\Block\Listing */ ?>
<?php $knowledgebase = $block->getAllKnowledgeBase(); ?>
<?php if (count($knowledgebase)): ?>
    <ul class="post-list post-list">
        <?php foreach($knowledgebase as $post): ?>
            <?php /* @var $post AudereCommerce\KnowledgeBase\Model\Post */ ?>
            <li class="post-item post-holder">
                <a href="<?php echo $block->getPostUrl($post); ?>" title="<?php $post->getTitle(); ?>" class="image" style="background-image: url(<?php echo $block->getListingImage($post); ?>);"></a>
                <div class="content">
                    <div class="top">
                        <h2 class="post-title">
                            <a href="<?php echo $block->getPostUrl($post); ?>" class="post-item-link"><?php echo $post->getTitle(); ?></a>
                        </h2>
                        <div class="post-description">
                            <?php if ($shortDescription = $post->getShortDescription()): ?>
                                <?php echo $shortDescription; ?>
                            <?php else: ?>
                                <?php echo $post->getPostIntroduction(); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="bottom">
                        <a href="<?php echo $block->getPostUrl($post); ?>" class="action primary" title="<?php echo $post->getTitle(); ?>">
                            <span><?php echo __('Read More'); ?></span>
                        </a>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php endif; ?>
