<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?= $block->escapeHtml(__('We can\'t find posts matching the selection.')) ?>
        </div>
    </div>
<?php else: ?>

    <?= $block->getStyleViewModel()->getStyle('Magefan_Blog::css/bootstrap-4.4.1-custom-min.css') ?>
    <?= $block->getAdditionalHtml() ?>
    <div class="post-list-wrapper">
        <?php $iterator = 1; ?>
        <ol class="post-list">
            <?php foreach ($_postCollection as $_post): ?>
                <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                $limit = 220;
                $shortDescription = strip_tags(str_replace('&nbsp;', '', $_post->getShortFilteredContent()));
                $blogHelper = $this->helper('AudereCommerce\AudereCommerce\Helper\Blog');
                /* @var $blogHelper AudereCommerce\AudereCommerce\Helper\Blog */
                ?>
                <li class="post-item post-holder post-holder-<?= (int)$_post->getId() ?>">
                    <?php if ($featuredImage = $_post->getFeaturedImage()): ?>
                        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>" class="image" style="background-image: url(<?php echo $featuredImage ?>);"></a>
                    <?php endif; ?>
                    <div class="content">
                        <div class="top">
                            <?php if ($postCategory = $blogHelper->getPostCategory($_post->getId())): ?>
                                <a href="<?php echo $blogHelper->getBlogCategoryUrl($postCategory); ?>" class="post-category">
                                    <span><?php echo $postCategory->getData('title'); ?></span>
                                </a>
                            <?php endif; ?>
                            <div class="blog-calendar-circle info-circle">
                                <div class="circle-inner">
                                    <div class="top-bar">
                                        <span class="month"><?php echo $_post->getPublishDate('M') ?></span>
                                    </div>
                                    <div class="day"><?php echo $_post->getPublishDate('d') ?></div>
                                    <div class="year"><?php echo $_post->getPublishDate('Y') ?></div>
                                </div>
                            </div>
                            <h2 class="post-title">
                                <a class="post-item-link"
                                   href="<?php echo $_postUrl ?>">
                                    <?php echo $_postName; ?>
                                </a>
                            </h2>
                            <div class="post-description clearfix">
                                <div class="post-text-hld clearfix">
                                    <?php if (strlen($shortDescription) > $limit): ?>
                                        <?php echo substr($shortDescription, 0, strrpos(substr($shortDescription, 0, $limit), ' ')) . '...'; ?>
                                    <?php else: ?>
                                        <?php echo $shortDescription; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <div class="bottom">
                            <a class="action primary" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                <?php echo __('Find Out More') ?>
                            </a>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
            <li class="hidden">
                <script type="text/javascript">
                    if (window.addthis) {
                        addthis.toolbox('.addthis_toolbox');
                    }
                </script>
            </li>
        </ol>
    </div>

    <?= $block->getToolbarHtml() ?>
    <?= $block->getChildHtml('addthisJs'); ?>
<?php endif; ?>
